name: Update docs

on:
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: jon-hagg/actions/publish-docs@main
        with:
          token: ${{ secrets.CI_TOKEN_CLONE_REPO }} 
